# Generated by Django 2.2.3 on 2019-09-24 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='new',
        ),
    ]
