# Generated by Django 2.2.3 on 2019-09-25 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_auto_20190924_2151'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='new',
            new_name='customer',
        ),
    ]
